welcome_title = "Willkommen beim Schlüsselkasten von Ziemann Engineering.\nWas möchtest du tun?"
booking = "Buchen"
borrowing = "Ausleihen"
returning = "Zurückgeben"
help_title = "Kurzanleitung"
help_intro = "An diesem Schlüsselkasten kannst du Schlüssel und andere Gegenstände ausleihen. So geht's:"
help_step1 = "Zuerst musst du über Flink buchen. Wenn du noch keinen Zugang zu Flink hast, wende dich bitte zu den Öffnungszeiten an die Rezeption."
help_step2 = "Nach Beginn des gebuchten Zeitraums kannst du den erhaltenen Code hier eingeben. Das entsprechende Fach öffnet sich und du kannst den Inhalt entnehmen."
help_step3 = "Bitte komme vor Ende deiner Buchung zurück und halte den Schlüsselanhänger rechts an das Lesegerät. Das Fach öffnet sich dann für die Rückgabe."
help_step4 = "Wenn du ein Problem hast, wende dich bitte zu den Öffnungszeiten an die Rezeption."
service_menu = "Service-Menü"
close_app = "App schliessen"
restart_app = "App neustarten"
open_all = "Alle öffnen"
mounting_mode = "Montage-Modus"
service_open = "Einzelnes Fach öffnen"
service_program = "NFC-Tag einem Fach zuweisen"
service_reset = "Fach-Tag-Zuweisung zurücksetzen"
booking_title = "Buchung"
booking_text = "Buchen kannst du via Flink-App oder auf maw.flink.coop.\nHier ist ein Link als QR-Code:"
borrowing_title = "Ausleihe"
borrowing_text = "Bitte gib deinen vierstelligen Code ein."
returning_title = "Rückgabe"
returning_text = "Bitte halte den Schlüsselanhänger an das Lesegerät auf der rechten Seite des Kastens."
status = "Status:"
code_invalid_title = "Code ungültig"
code_invalid_announcement = "Dieser Code ist aktuell nicht gültig. Bitte prüfe deine Buchung."
code_error_title = "Fehler"
code_error_announcement = "Beim Prüfen des Codes ist ein Fehler aufgetreten. Bitte versuche es später nochmals."
invalid_compartment_title = "Ungültiges Fach"
invalid_compartment_text = "Fach {compartment} existiert nicht."
open_compartment_title = "Fach öffnen"
open_compartment_text = "Fach {compartment} wird geöffnet."
compartment_opened_title = "Fach wurde geöffnet"
compartment_opened_announcement = "Bitte Fach {compartment} wieder schliessen."
compartment_opened_question_borrow = "Hast du den Inhalt entnommen?"
compartment_opened_question_return = "Hast du den Inhalt zurückgelegt?"
compartment_opened_question_service = "Möchtest du ein weiteres Fach öffnen?"
compartment_not_opened = "Fach {compartment} hat sich nicht geöffnet."
try_again = "Erneut versuchen?"
yes = "Ja"
no = "Nein"
nfc_program_title = "NFC-Tag programmieren"
nfc_program_text = "Bitte den NFC-Tag für Fach {comp} rechts an den Leser halten, bis der Vorgang abgeschlossen ist."
nfc_assigning = "NFC-Tag wird Fach {comp} zugewiesen."
nfc_not_found = "Kein NFC-Tag erkannt."
nfc_invalid_comp = "Fach {comp} ist nicht gültig."
reset_title = "Fach zurückgesetzt"
reset_text = "Die gespeicherten NFC-Tags für Fach {comp} wurden gelöscht."
