welcome_title = "Bienvenue à la boîte à clés de Ziemann Engineering.\nQue souhaitez-vous faire ?"
booking = "Réserver"
borrowing = "Emprunter"
returning = "Rendre"
help_title = "Guide rapide"
help_intro = "Dans cette boîte à clés, vous pouvez emprunter des clés et d'autres objets. Voici comment faire :"
help_step1 = "Vous devez d'abord réserver via Flink. Si vous n'avez pas encore accès à Flink, veuillez vous adresser à la réception pendant les heures d'ouverture."
help_step2 = "Après le début de la période réservée, vous pouvez saisir ici le code reçu. Le compartiment correspondant s'ouvrira et vous pourrez prendre le contenu."
help_step3 = "Veuillez revenir avant la fin de votre réservation et tenir le porte-clés à droite contre le lecteur. Le compartiment s'ouvrira alors pour le retour."
help_step4 = "Si vous avez un problème, veuillez vous adresser à la réception pendant les heures d'ouverture."
service_menu = "Menu de service"
close_app = "Fermer l'appli"
restart_app = "Redémarrer appli"
open_all = "Tout ouvrir"
mounting_mode = "Ouvrir les compartiments pour le montage"
service_open = "Ouvrir un compartiment individuel"
service_program = "Assigner un tag NFC" #"Attribuer un tag NFC à un compartiment"
service_reset = "Réinitialiser l'attribution des tags" #"Réinitialiser le tag du compartiment" # "Réinitialiser l'attribution du tag au compartiment"
booking_title = "Réservation"
booking_text = "Vous pouvez réserver via l'application Flink ou sur maw.flink.coop.\nVoici un lien sous forme de QR code :"
borrowing_title = "Emprunt"
borrowing_text = "Entrez votre code à 4 chiffres."
returning_title = "Retour"
returning_text = "Veuillez tenir le porte-clés contre le lecteur situé à droite de la boîte."
status = "Statut :"
code_invalid_title = "Code invalide"
code_invalid_announcement = "Ce code n'est actuellement pas valide. Veuillez vérifier votre réservation."
code_error_title = "Erreur"
code_error_announcement = "Une erreur s'est produite lors de la vérification du code. Veuillez réessayer plus tard."
invalid_compartment_title = "Compartiment invalide"
invalid_compartment_text = "Le compartiment {compartment} n'existe pas."
open_compartment_title = "Ouvrir le compartiment"
open_compartment_text = "Le compartiment {compartment} va s'ouvrir."
compartment_opened_title = "Le compartiment a été ouvert"
compartment_opened_announcement = "Veuillez refermer le compartiment {compartment}."
compartment_opened_question_borrow = "Avez-vous pris le contenu ?"
compartment_opened_question_return = "Avez-vous remis le contenu ?"
compartment_opened_question_service = "Voulez-vous ouvrir un autre compartiment ?"
compartment_not_opened = "Le compartiment {compartment} ne s'est pas ouvert."
try_again = "Réessayer ?"
yes = "Oui"
no = "Non"
cancel = "Annuler"
nfc_program_title = "Programmer le tag NFC"
nfc_program_text = "Veuillez tenir le tag NFC pour le compartiment {comp} à droite contre le lecteur jusqu'à la fin de l'opération."
nfc_assigning = "Le tag NFC est attribué au compartiment {comp}."
nfc_not_found = "Aucun tag NFC détecté."
nfc_invalid_comp = "Le compartiment {comp} n'est pas valide."
reset_title = "Compartiment réinitialisé"
reset_text = "Les tags NFC enregistrés pour le compartiment {comp} ont été supprimés."
settings = "Configuration"
settings_sound = "Retour sonore"
settings_haptic = "Retour haptique"